### ISSUE TITLE
Config not applied using Yaml formatted with tabs

### ISSUE THREAD

**Issue by Grawl** [michael-ciniawsky/postcss-load-config#124]
## Problem

Config file `.postcssrc.yaml` is not applied if I use Yaml formatted with tabs.

Worked with two spaces.

## Details

Working:

```yml
plugins:
  postcss-axis: {}
  postcss-short: {}
  postcss-position-alt: {}
  autoprefixer: {}
```

Not working:

```yml
plugins:
	postcss-axis: {}
	postcss-short: {}
	postcss-position-alt: {}
	autoprefixer: {}
```

## Error Logs

There is no error when I using [`poi`](https://poi.js.org)

## Environment

Please provide information about your environment.

| OS              | Node      | yarn       | PostCSS   |
|:---------------:|:---------:|:---------:|:---------:|
| macOS 10.13.2 | `9.3.0 ` | `1.3.2` | `5.2.18` |
