### ISSUE TITLE
Case sensitive config will fail to load on Linux systems 

### ISSUE THREAD

**Issue by sgreav** [michael-ciniawsky/postcss-load-config#138]
#### Issue description
When loading a config file, case sensitivity is important on Linux systems. This is not the case on Windows or MacOS.

#### Steps to reproduce the issue

1.  Create a project using postcss loader and webpack 4, with the following Css loader rule: 
```css: {
    test: /\.css$/,
    use: [
      'style-loader',
      MiniCssExtractPlugin.loader,
      {
        loader: 'css-loader',
        options: {
          importLoaders: 1,
          sourceMap: true
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          config: {
            path: path.resolve(__dirname, 'postCSS.config.js')
          },
          sourceMap: true
        }
      }
    ]
  }
```
(note the case of postCSS.config.js in path.resolve)

2. Create a postcss config file named `postCSS.config.js` with any valid content.
3.  Build on windows / macOS, all will work fine.
4.  Switch to a linux machine and build there, the system's case sensitivity will cause the build to fail

#### What's the expected result?

- It is expected that the file will be found on all systems, given the filename case matches that in `options.config.path` 

#### What's the actual result?

- A build failure, caused by the error: 
`Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /some-app/some-package/postCSS.config.js`

#### Additional details / screenshot

I am assuming that somewhere the case sensitivity provided in `options.config.path` is not being honored. It would be nice to get this fixed, but if that is not possible, an error message tip, suggesting that `postcss.config.js`'s case is important would be greatly appreciated.
